version: '3.0'
services:
    # WordPress
    wordpress:
        image: wordpress:latest
        depends_on: 
            - db
        volumes: ['./:/var/www/html']
        ports: 
            - "4000:80"
        restart: always
        environment: 
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        networks: 
            - wpsite
    # Database
    db:
        image: mysql:5.7
        volumes: 
            - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks: 
            - wpsite
    # phpmyadmin
    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: 
            - "4001:80"
        environment: 
            PMA_HOST: db
            MY_SQL_ROOT_PASSWORD: wordpress
        networks: 
            - wpsite
networks: 
    wpsite:
volumes: 
    db_data: